### PR TITLE
add text QRCode

### PR DESCRIPTION
**Pull request by xrdavies**
Add text QRCode for development.

Use  RunBot(cmdQrCode=True) to display QRCode in term.

### CODE REVIEW

**Comment by xrdavies** [comment]
5f0e33a6-47f8-4a5f-bf36-ca6649a54c8d

Screen shot for text QRCode

**Comment by Yijia-Zhou** [comment]
赞！

**Comment by jim4node** [comment]
这个好!

**Comment by pandolia** [comment]
试了一下，在 mate-terminal 下的效果不是很好，扫不出来。

screenshot-1

**Comment by xrdavies** [comment]
@pandolia 
mate-term for marc or windows? I will fix it soon.

**Comment by xrdavies** [comment]
@pandolia

Could you try this command to see the return value?
>>> import wcwidth
>>> wcwidth.wcwidth(u'\u2588')

Normally it will return 1 for Mac OS. Please let me know the return value of mate-term. Thanks.

**Comment by kairyu** [comment]
@xrdavies 
I have the same issue with @pandolia. I have tested the command you said and the return value is 1 in my environment. After I changed ```blockCount = 2```, everything works fine for me.

**Environment**
- Host OS: Linux (Ubuntu 16.04)
- Host Term: xterm-256color
- Client OS: Windows7
- Client Term: putty
- Font: DejaVu Sans Mono

**Comment by pandolia** [comment]
@xrdavies 非常感谢！我在 windows 自带的 cmd 下测试了一下，wcwidth 返回 1 。也扫不出来，把 blockCount 改成 2 也扫不出来。等会在 Linux（Debian8.5） 的 mate-terminal 下再测试一下。

**Comment by pandolia** [comment]
Linux（Debian8.5） 的 mate-terminal 下，wcwidth 返回 1 。我把 blockCount 改成 2 ,效果好很多了。但还是扫不出来。
screenshot-2

**Comment by pandolia** [comment]
@xrdavies 另外，我已经去掉了你原来在 RunBot 函数内增加的参数 cmdQrCode ，改为命令行参数启动，如： qqbot -cq ，或者在配置文件中设置 cmdQrcode 项的值。

**Comment by pandolia** [comment]
Linux（Debian8.5） 的 xterm 下，把 blockCount 改成 2 ，图片有点拉长，不过可以扫出来。
screenshot-3

**Comment by xrdavies** [comment]
@kairyu

Thanks for test. 

@pandolia 

The root cause is different terms will treat characters with different width. With wcwidth, it will calculate the width for term. I will fix it with wcwidth.

But for mate-term, I'm afraid it will not work...  :( 
The line spacing is quite huge that not possible to be scanned. Will try to find other solution for mate-term and windows cmd.

**Comment by xrdavies** [comment]
@pandolia

Have noticed that the image attached for mate-terminal is quite strange, that the color for qrcode is reversed, while with xterm, it is normal.

So need more code to detect the term settings. Especially for background color and front color.

For windows, could you attach a screen shot?

**Comment by xrdavies** [comment]
@pandolia 

Please find the new PR.
It solved QRCode on windows, and maybe mate-terminal. Since force term to use white and black for QRCode.

Please try this one.

**Comment by pandolia** [comment]
可能跟终端的背景色也有关系。mate-terminal背景色是白色，所以打印出来的图片有空隙。xterm背景色是黑色，就没有空隙。

**Pull request merged**
